CREATE TABLE SalesReps (
  id SERIAL PRIMARY KEY,
  firebase_id VARCHAR(255) UNIQUE NOT NULL, -- Added UNIQUE constraint, good practice
  name VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'available',
  total_customers INTEGER DEFAULT 0, -- Added comma
  finished_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL -- Corrected type
);

CREATE TABLE Customers (
  id SERIAL PRIMARY KEY,
  rep_id INTEGER REFERENCES SalesReps(id) ON DELETE SET NULL, -- Ensure SalesReps is capitalized if table name is
  customer_name VARCHAR(100) NOT NULL,
  status VARCHAR(50) DEFAULT 'waiting',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Added TIME ZONE, good practice
);

CREATE TABLE public.inventory_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_type_id integer NOT NULL,
  unique_identifier text NOT NULL UNIQUE,
  status text NOT NULL,
  location text NOT NULL,
  added_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  color text,
  size text
);

CREATE TABLE public.supply_orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_type_id integer NOT NULL,
  quantity integer NOT NULL,
  ordered_at timestamp with time zone NOT NULL DEFAULT now(),
  expected_at timestamp with time zone,
  status text NOT NULL
);

ALTER TABLE public.supply_orders
  ADD CONSTRAINT fk_supply_orders_product_types
    FOREIGN KEY (product_type_id)
    REFERENCES public.product_types(id)
    ON DELETE CASCADE;
